services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /home/www/.ssh:/root/.ssh:ro
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - laravel
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}


volumes:
  mysql_data:

networks:
  laravel:
